# === Data Directories ===
train_dir: st1/train
val_dir: st1/val
test_path: st1/val

# === Input Configuration ===
input_shape: [512, 512, 3]
batch_size: 8

# === Model Settings ===
use_pretrained_model: false
pretrained_model_path: "modelli/4_640_640_3_20250610_154520"  # Inserire se use_pretrained_model è true
dropout: 0.95
gaussian_noise: 2
classes : 2

# === Training Configuration ===
epochs: 600
lr: 0.001
decay_after_n_epochs: 5

# === Callbacks and Metrics ===
checkpoint_filepath: modelli/
monitor_metric: val_binary_accuracy
mode: max

label_dictionary = {label: idx for idx, label in enumerate(sorted(os.listdir(train_dir)))}

# === Augmentation Parameters ===
show_augmentations: false
augmentation:
  train:
    rescale: 0.00392156862745098  # 1./255.
    rotation_range: 3
    zoom_range: 0.08
    width_shift_range: 0.03
    height_shift_range: 0.03
    brightness_range: [0.7, 1.3]
    vertical_flip: True
    horizontal_flip: True
    fill_mode: constant
    cval: 0
  val:
    rescale: 0.00392156862745098  # 1./255.

auto_split:
  enabled: true
  source_dir: "st1"
  output_dir: "tmp_split"
  val_split: 0.085
  test_split: 0.05
