augmentation:
  train:
    brightness_range:
    - 0.5
    - 1.13
    cval: 0
    fill_mode: constant
    height_shift_range: 0.03
    horizontal_flip: true
    rescale: 0.004
    rotation_range: 3
    vertical_flip: true
    width_shift_range: 0.03
    zoom_range: 0.08
  val:
    rescale: 0.004
auto_split:
  enabled: true
  output_dir: dataset
  source_dir: st1
  test_split: 0.05
  val_split: 0.1
batch_size: 16
checkpoint_filepath: modelli/
classes: 2
decay_after_n_epochs: 5
dropout: 0.5
epochs: 600
gaussian_noise: 1
input_shape: (512, 512, 3)
lr: 0.001
mode: max
monitor_metric: val_binary_accuracy
pretrained_model_path: ''
show_augmentations: true
test_path: dataset\test
train_dir: dataset\train
use_pretrained_model: false
val_dir: dataset\val
